### ISSUE TITLE
Interior cutouts still missing from Gerber

### ISSUE THREAD

**Issue by leomcelroy** [leomcelroy/svg-pcb#40]
Bringing to @kr15h 's attention. Despite merging #37 there still seem to be some issues with interior shapes.

Here is a design in SVG-PCB

<img width="573" alt="Screen Shot 2023-04-04 at 10 32 22 PM" src="https://user-images.githubusercontent.com/27078897/229966337-02b4f0bd-dba8-452d-9c78-0e21ebaa2be9.png">

And the Gerber in tracespace

<img width="654" alt="Screen Shot 2023-04-04 at 10 33 05 PM" src="https://user-images.githubusercontent.com/27078897/229966411-8b5dc765-2179-4324-bd31-8d13fdea7931.png">

Here is the test file:

```
/* 
@version: v0.0.1

a basic starter design 
*/

/* -- DECLARE_PCB -- */
const board = new PCB();

/* -- DECLARE_COMPONENTS -- */

// constants
const width = 1;
const height = 1;

// board size and shape
let interior = [
  path(
    pt(-0.5, 0.5),
    pt(0.5, 0.5),
    pt(0.5, -0.5),
    pt(-0.5, -0.5),
  ),
  path(
  pt(-0.25, 0.25),
  pt(-0.25, 0),
  pt(-0.1, 0),
  pt(-0.1, 0.25),)
]

board.addShape("interior", interior);

/* -- ADD_COMPONENTS -- */

/* -- RENDER_PCB -- */
const limit0 = pt(-0.55, -0.55);
const limit1 = pt(0.55, 0.55);
const xMin = Math.min(limit0[0], limit1[0]);
const xMax = Math.max(limit0[0], limit1[0]);
const yMin = Math.min(limit0[1], limit1[1]);
const yMax = Math.max(limit0[1], limit1[1]);

renderPCB({
  pcb: board,
  layerColors: {
    "interior": "#002d00ff",
    "B.Cu": "#ff4c007f",
    "F.Cu": "#ff8c00cc",
    "drill": "#ff3300e5",
    //"padLabels": "#ffff99e5",
    "componentLabels": "#00e5e5e5",
  },
  limits: {
    x: [xMin, xMax],
    y: [yMin, yMax]
  },
  mm_per_unit: 25.4
});


```

**Comment by kr15h** [comment]
Oh yes I see. Seeing this in KiCad Gerber viewer with this. 
![Screenshot from 2023-04-05 10-29-11](https://user-images.githubusercontent.com/817241/230011766-dd8bbd93-e2b4-4277-8da8-9a2f513ef061.png)
The solution probably is to double-check if first point is also the last.

**Comment by kr15h** [comment]
Now it works in tracespace. There was one more issue with zero values being formatted into void values in Gerber which caused invisible lines in tracespace.
![Screenshot from 2023-04-05 10-53-01](https://user-images.githubusercontent.com/817241/230017108-799d1080-63dc-436b-9e72-994894831ac1.png)
