### ISSUE TITLE
Need link to footprint for each component placed

### ISSUE THREAD

**Issue by kr15h** [leomcelroy/svg-pcb#43]
There is data lost when components are made out of footprints and some of that data is useful when exporting to KiCad, for example. How about adding a reference to footprint in each board.pcb.components item? One of the things that is getting lost is the pin numbering. Pin labels are fine, but the numbering is more important in KiCad.

**Comment by leomcelroy** [comment]
I actually added this yesterday on my dev branch. It's got a few more changes we may not want to merge yet but I can push that one.

**Comment by kr15h** [comment]
I figured it out somehow, but the numbering of the pads could be off the way I did it. I can rebase and adjust when you merge that later.

**Comment by kr15h** [comment]
I noticed the RefDes, but what would be VERY useful is a reference to the original footprint from each component placed. It would be also perfect if vias would point to an object similar to footprint definition so there would be no need for special case handling. I could try to add this myself unless you have something cooking in your dev branch.

**Comment by kr15h** [comment]
> I figured it out somehow, but the numbering of the pads could be off the way I did it. I can rebase and adjust when you merge that later.

And this solution breaks as soon I open up a design with vias.

**Comment by kr15h** [comment]
I will try with the new `padShapes`. Maybe it will work.

**Comment by kr15h** [comment]
Ah, no, I still would need the pad numbering from the original footprint.

**Comment by leomcelroy** [comment]
I'm including this in the component now. It's a bit messy but shouldn't lose anything.

<img width="620" alt="Screen Shot 2023-04-08 at 4 48 49 PM" src="https://user-images.githubusercontent.com/27078897/230742030-40a92120-a5b3-47ee-85b8-f2579ca030ce.png">
