### ISSUE TITLE
Need layers per pad not pads per layer

### ISSUE THREAD

**Issue by kr15h** [leomcelroy/svg-pcb#44]
There is probably a reason why in KiCad there is a layer list for each pad. Pad geometry is more complex and thus it makes sense not to repeat it too much. Layer names are simple, thus it makes sense to repeat them per each pad rather than repeat pad geometry for each layer. What I propose is:
 
```
component: {
  pads: [
    {number: 1, label: "GND", shape: {...depending on type...}, layers:["F.Cu", "B.Cu", ...]}
  ]
}
```

**Comment by leomcelroy** [comment]
Addressed with issue #43 I believe.
