### ISSUE TITLE
Vias to be kept in a separate global array

### ISSUE THREAD

**Issue by kr15h** [leomcelroy/svg-pcb#45]
It would be actually nice to have vias separately from components as vias are not components in a regular sense. The  object structure is different, and all you need for a via are these:
- pad outer diameter
- pad inner diameter or drill
- list of layers the via connects

If there are global variables such as `footprints` and `components`, vias could have their own `vias` storage.

**Comment by leomcelroy** [comment]
This is addressed with the way drills are handled in #50
